name: Update project
run-name: ${{ github.actor }} is testing out GitHub Actions and Screenshot tests 🚀
on: [push]
jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [ 18.x ]
    # The runners that the job will run on
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build ladle
        run: npm run build

      - name: Build ladle
        run: npm run build-storybook

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.0.3
