on: workflow_dispatch

jobs:
  lost-pixel-update:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build storybook
        run: npm run build-storybook

      - name: Lost Pixel
        id: lp
        uses: lost-pixel/lost-pixel@v3.3.0
        env:
          LOST_PIXEL_MODE: update
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        if: ${{ failure() && steps.lp.conclusion == 'failure' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}